MODULE_NAME="_PYBASH"
MODULE_DATA_DIR=$PYBASH_DATA_DIR/$MODULE_NAME
if [ ! -e $MODULE_DATA_DIR ]; then
  mkdir $MODULE_DATA_DIR
fi

MODULE_LIST_PATH=$PYBASH_DATA_DIR/installed_modules.txt
if [ ! -e $MODULE_LIST_PATH ]; then
  echo $MODULE_NAME >> $MODULE_LIST_PATH
fi
